# TODO: Utiliser :latest lorsque le bug suivant sera corrigé:
#       https://gitlab.alpinelinux.org/alpine/aports/-/issues/15742
FROM alpine:3.18

RUN apk add --no-cache python3 py3-django texlive-full

EXPOSE 8000

# Start the app
#CMD ["python", "manage.py", "runserver, "0.0.0.0:8000]
